### ISSUE TITLE
Issue with alpine

### ISSUE THREAD

**Issue by chevdor** [jeanblanchard/docker-java#2]
Hello Jean

I am using your image for a while (jre-8) and never had an issue.
I saw that the java-jre-8 image depends on some of your own images and in the end you use the alpine image.
I am getting since today the following issue:

```
 ---> Running in d35c6c04bf6a
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-4.alpinelinux.org/alpine/v3.2/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.abd86498.tar.gz: No such file or directory
1 errors; 18 distinct packages available
The command '/bin/sh -c apk update &&   apk add wget gpgme &&   mkdir /nxt-boot &&   mkdir /nxt &&   cd /' returned a non-zero code: 1
```

I did not have such an issue exactly a month ago.

I tested the alpine image itself (docker run alpine:latest ls -al) and it runs fine so there may be an issue in one of your images. Are you aware of something?

**Comment by jeanblanchard** [comment]
Hi
From your comment I'm not sure when and where you are getting this error. But anyway it looks like an error on the alpine webserver. Do you still have a problem if you try again ?

**Comment by chevdor** [comment]
Hi,

The issue happened while doing a docker build either locally or from docker hub.
The issue is resolved now and indeed, it looks like a temporary issue with alpine servers.
