### ISSUE TITLE
Add JCE to image

### ISSUE THREAD

**Issue by unoexperto** [jeanblanchard/docker-java#3]
Jean, could  you please add this to the image  ?

curl -jkLH "Cookie: oraclelicense=accept-securebackup-cookie" -o jce_policy-8.zip http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip

it's necessary for certain types of encryption APIs. For instance it wouldn't be possible to unpack password protected d7z archive using Apache Commons-Compress library.

**Comment by jeanblanchard** [comment]
Hey, looks like this ticket flew below my radar...
I've added the unlimited policy to the images now.
@unoexperto Please tell me if your use case works now, this is rather untested for now...
