### ISSUE TITLE
When will the jdk-8 tag be rebuilded based on glibc 2.25?

### ISSUE THREAD

**Issue by gzm55** [jeanblanchard/docker-java#6]
jeanblanchard/alpine-glibc:latest is update to 3.5_2.25-r0, and when this image will be rebuild?

**Comment by jeanblanchard** [comment]
3 days ago, supposedly! But I didn't see that [the build](https://circleci.com/gh/jeanblanchard/docker-java/39) failed while downloading the JDK from Oracle.
It should be [ok now](https://circleci.com/gh/jeanblanchard/docker-java/41).
